### ISSUE TITLE
راهنمایی در مورد کتابخانه

### ISSUE THREAD

**Issue by DavisMillier** [ebraminio/PInvokeSerialPort#3]
سلام
بابت زحمتی که کشیدید تشکر.
لطف میکنید در مورد این کتابخانه کمی برای من توضیح بدید ؟
من متوجه شدم خیلی کتابخانه موجود در دات نت قابلیت اطمینان نداره و ممکنه دچار تاخیر در دریافت و یا حتی از بین رفتن داده ها بشه
برای همین در مورد WIN32API 
کمی مطالعه کردم کمی مطالب برایم جدید و سخت بود . خواستم توضیحاتی بدید.
تشکر میکنم.

**Comment by ebraminio** [comment]
سلام!‌ کد این کتابخانه از
https://web.archive.org/web/20150527104136/http://msdn.microsoft.com/en-us/magazine/cc301786.aspx
گرفته شده، خلاصه‌ش این هست که کامپوننتی که همراه دات‌نت داده‌اند یه محدودیت‌هایی دارد ولی با صدا زدن مستقیم‌تر کرنل ویندوز بعضی از این محدودیت‌ها ورداشته می‌شود، وین۳۲ای‌پی‌آی هم به مجموعهٔ توابعی گفته می‌شود که محیط ویندوز برای برنامه‌‌نویس قرار می‌دهد که مجموعهٔ گسترده‌ای از توابع را شامل می‌شود که یه سری از جملهٔ همین توابع کرنل۳۲ که برای پیاده‌سازی این کتابخانه نیاز است. اینکه می‌گویید داده‌های از بین می‌رود باید حتماً ببینید مشکل از کجاس چون اگه زمان زباله جمع‌کن برایتان دردسر درست می‌کند احتمالاً در نهایت چاره‌ای جز بازنویسی برنامه‌تان با سی ندارید هر چند که فکر می‌کنم بافر کردن کرنل ویندوز برایتان احتمالاً کافی باشد. ایشو را می‌بندم سوالی ولی داشتید حتماً بفرمایید
